//
//  PDAbraConstants.h
//  PopdeemSDK
//
//  Created by Niall Quinn on 14/09/2016.
//  Copyright © 2016 Popdeem. All rights reserved.
//

#ifndef PDAbraConstants_h
#define PDAbraConstants_h

extern NSString *const ABRA_URL;
extern NSString *const ABRA_EVENT_PATH;
extern NSString *const ABRA_TOKEN_PATH;

extern NSString *const ABRA_KEY_USER_ID;
extern NSString *const ABRA_KEY_EVENT;
extern NSString *const ABRA_KEY_TRAITS;
extern NSString *const ABRA_KEY_PROJECT_TOKEN;
extern NSString *const ABRA_KEY_TAG;
extern NSString *const ABRA_KEY_PROPERTIES;

extern NSString *const ABRA_EVENT_PAGE_VIEWED;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_LOGIN_TAKEOVER;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_REWARDS_HOME;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_ACTIVITY_FEED;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_WALLET;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_INSTA_TUTORIAL_MODULE_ONE;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_INSTA_TUTORIAL_MODULE_TWO;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_CONNECT_INSTAGRAM;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_SETTINGS;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_INBOX;
extern NSString *const ABRA_PROPERTYVALUE_PAGE_CLAIM;

extern NSString *const ABRA_PROPERTYNAME_REWARD_TYPE;
extern NSString *const ABRA_PROPERTYVALUE_REWARD_TYPE_COUPON;
extern NSString *const ABRA_PROPERTYVALUE_REWARD_TYPE_SWEEPSTAKE;

extern NSString *const ABRA_PROPERTYNAME_REWARD_ACTION;
extern NSString *const ABRA_PROPERTYVALUE_REWARD_ACTION_CHECKIN;
extern NSString *const ABRA_PROPERTYVALUE_REWARD_ACTION_PHOTO;

extern NSString *const ABRA_PROPERTYNAME_NETWORKS_AVAILABLE;
extern NSString *const ABRA_PROPERTYVALUE_NETWORKS_AVAILABLE_FACEBOOK;
extern NSString *const ABRA_PROPERTYVALUE_NETWORKS_AVAILABLE_TWITTER;
extern NSString *const ABRA_PROPERTYVALUE_NETWORKS_AVAILABLE_INSTAGRAM;

extern NSString *const ABRA_EVENT_CLICKED_CLOSE_LOGIN_TAKEOVER;
extern NSString *const ABRA_EVENT_CLICKED_CLOSE_LOGIN_SIGNUP;
extern NSString *const ABRA_EVENT_CLICKED_CLOSE_INSTAGRAM_CONNECT;
extern NSString *const ABRA_EVENT_CLICKED_NEXT_INSTAGRAM_TUTORIAL;
extern NSString *const ABRA_EVENT_CLICKED_SIGN_IN_INSTAGRAM;

extern NSString *const ABRA_EVENT_CLAIMED;
extern NSString *const ABRA_PROPERTYNAME_SOCIAL_NETWORKS;
extern NSString *const ABRA_PROPERTYVALUE_SOCIAL_NETWORK_FACEBOOK;
extern NSString *const ABRA_PROPERTYVALUE_SOCIAL_NETWORK_TWITTER;
extern NSString *const ABRA_PROPERTYVALUE_SOCIAL_NETWORK_INSTAGRAM;
extern NSString *const ABRA_PROPERTYNAME_PHOTO_ATTACHED;
extern NSString *const ABRA_PROPERTYNAME_REWARD_TYPE;

extern NSString *const ABRA_EVENT_CONNECTED_ACCOUNT;
extern NSString *const ABRA_PROPERTYNAME_SOCIAL_NETWORK;
extern NSString *const ABRA_PROPERTYNAME_SOURCE_PAGE;
extern NSString *const ABRA_PROPERTYVALUE_SOURCE_PAGE_TAKEOVER;
extern NSString *const ABRA_PROPERTYVALUE_SOURCE_PAGE_REWARD_LIST;
extern NSString *const ABRA_PROPERTYVALUE_SOURCE_PAGE_SETTINGS;

extern NSString *const ABRA_PROPERTYNAME_PERMISSIONS;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_EMAIL;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_EDUCATION;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_PUBLIC_PROFILE;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_USER_BIRTHDAY;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_USER_FRIENDS;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_USER_POSTS;
extern NSString *const ABRA_PROPERTYVALUE_PERMISSIONS_TAGGABLE_FRIENDS;

extern NSString *const ABRA_EVENT_FACEBOOK_DENIED_PUBLISH_PERMISSIONS;
extern NSString *const ABRA_EVENT_ADDED_CLAIM_CONTENT;
extern NSString *const ABRA_PROPERTYNAME_TEXT;
extern NSString *const ABRA_PROPERTYNAME_PHOTO;
extern NSString *const ABRA_PROPERTYNAME_TAGGED_FRIENDS;

extern NSString *const ABRA_EVENT_RECEIVED_ERROR_ON_CLAIM;
extern NSString *const ABRA_PROPERTYNAME_NO_HASHTAG;
extern NSString *const ABRA_PROPERTYNAME_NO_NETWORK_SELECTED;
extern NSString *const ABRA_PROPERTYNAME_NO_PHOTO;

extern NSString *const ABRA_EVENT_TOGGLED_SOCIAL_BUTTON;
extern NSString *const ABRA_PROPERTYNAME_SOCIAL_BUTTON_TYPE;
extern NSString *const ABRA_PROPERTYNAME_SOCIAL_BUTTON_STATE;
extern NSString *const ABRA_PROPERTYVALUE_SOCIAL_BUTTON_STATE_ON;
extern NSString *const ABRA_PROPERTYVALUE_SOCIAL_BUTTON_STATE_OFF;

extern NSString *const ABRA_EVENT_REDEEMED_REWARD;
extern NSString *const ABRA_PROPERTYNAME_REWARD_NAME;
extern NSString *const ABRA_PROPERTYNAME_REWARD_ID;

extern NSString *const ABRA_EVENT_LOGIN;
extern NSString *const ABRA_EVENT_LOGOUT;
extern NSString *const ABRA_EVENT_SIGNUP;

extern NSString *const ABRA_EVENT_DISCONNECT_SOCIAL_ACCOUNT;

extern NSString *const ABRA_USER_TRAITS_ID;
extern NSString *const ABRA_EVENT_ONBOARD;
extern NSString *const ABRA_USER_TRAITS_FIRST_NAME;
extern NSString *const ABRA_USER_TRAITS_LAST_NAME;
extern NSString *const ABRA_USER_TRAITS_EMAIL;
extern NSString *const ABRA_USER_TRAITS_DOB;
extern NSString *const ABRA_USER_TRAITS_GENDER;
extern NSString *const ABRA_USER_TRAITS_CITY;
extern NSString *const ABRA_USER_TRAITS_COUNTRY_CODE;
extern NSString *const ABRA_USER_TRAITS_REGION;
extern NSString *const ABRA_USER_TRAITS_TIME_ZONE;
extern NSString *const ABRA_USER_TRAITS_PUSH_NOTIFICATIONS_ENABLED;
extern NSString *const ABRA_USER_TRAITS_IP;

extern NSString *const ABRA_PROPERTYNAME_ERROR;
extern NSString *const ABRA_PROPERTYVALUE_ERROR_HASHTAG;
extern NSString *const ABRA_PROPERTYVALUE_ERROR_TOOMANYCHARS;
extern NSString *const ABRA_PROPERTYVALUE_ERROR_NOPHOTO;

extern NSString *const ABRA_EVENT_DENIED_LOCATION;
extern NSString *const ABRA_EVENT_DENIED_PUSH_NOTIFICATIONS;

extern NSString *const ABRA_EVENT_CANCELLED_FACEBOOK_LOGIN;
#endif /* PDAbraConstants_h */
