fastlane_version "1.63.0"
default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["GITHUB_TOKEN"] = "75edf67be15cda9c710fa0e22014731ec247eaf5"
  end

  lane :podtest do
    desc "**Checking cocoapods all OK**"
    sh "pod spec lint ../PopdeemSDK.podspec --allow-warnings --use-libraries"
    sh "pod lib lint ../PopdeemSDK.podspec --allow-warnings --use-libraries"
    slack(
      channel: "mobile",
      message: "PopdeemSDK podpec and lib linted OK",
      success: "true"
    )
  end

  lane :build_static_library do
    sh "xctool -workspace ../PopdeemSDK.xcworkspace \
                -scheme PopdeemSDK \
                clean"
    sh "xctool -workspace ../PopdeemSDK.xcworkspace \
                -scheme PopdeemSDK \
                -configuration Release \
                -sdk 'iphoneos9.3' \
                TARGET_BUILD_DIR='../build' \
                BUILT_PRODUCTS_DIR='../build' \
                build"
  end

  lane :test do
  end

  lane :deploy do
    desc "**Deploying PopdeemSDK**"

    #prelim tests before bump
    podtest
    ensure_git_status_clean

    new_version = version_bump_podspec(path: "PopdeemSDK.podspec", bump_type: "patch")
    puts "After bump Pods Version: #{new_version}"

    sh "git add ."
    sh "git commit -m \"Deploying via Fastlane - version #{new_version}\""
    sh "git push origin master"
    sh "git tag #{new_version}"
    sh "git push --tags"

    clean_cocoapods_cache

    sh "pod trunk push ../PopdeemSDK.podspec --allow-warnings --use-libraries"

    #Release to github
    build_static_library
    github_release = set_github_release(
            repository_name: "Popdeem/Popdeem-SDK-iOS",
            api_token: ENV['GITHUB_TOKEN'],
            name: "Release #{new_version}",
            tag_name: "#{new_version}",
            description: "PopdeemSDK Latest Release",
            commitish: "master",
            upload_assets: ["../build/libPopdeemSDK.a"]
            )

    puts(current_version)
    slack(
      channel: "mobile",
      message: ":pdlogo: Deployed PopdeemSDK.... :rocket:",
      success: true
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    if ENV['SLACK_URL']
      slack(
        channel: "mobile",
        message: ":bangbang: Fastlane error in PopdeemSDK: " + exception.message,
        success: false
        )
    end
  end

  private_lane :current_version do |options|
    puts "Checking the latest version on Cocoapods"
  end
end
