# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.37.0"

default_platform :ios


platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
  desc "**Deploying PopdeemSDK**"
  #Need to do full cocoapods release cycle here
    puts(current_version)
    slack(
      channel: "mobile",
      message: "Deploying PopdeemSDK.... :rocket:",
      success: true
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
    if ENV['SLACK_URL']
    slack(
      channel: "mobile",
      message: "Fastlane error in PopdeemSDK: " + exception.message,
      success: false
    )
  end

  end

  private_lane :current_version do |options|
    puts "Checking the latest version on Cocoapods"
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
